### ISSUE TITLE
Alert Details non-existent 

### ISSUE THREAD

**Issue by ikifar2012** [michaeldavie/env_canada#19]
I have been using the environment Canada integration in home assistant and the docs mention a alert details attribute for the sensors but that does not seem to exist. Has this feature been removed or broken? Do you plan on adding it back?

**Comment by michaeldavie** [comment]
Yes, unfortunately this is currently broken. It had to be removed due to an architectural decision to ban web scraping (https://github.com/home-assistant/architecture/blob/master/adr/0004-webscraping.md). I'm working on adding this functionality back once I find another source of the data. Sorry for the inconvenience.
