### ISSUE TITLE
Colours not locked to fixed mm/h values

### ISSUE THREAD

**Issue by deftdawg** [michaeldavie/env_canada#31]
Got this running as a custom component for the moment.  It looks really nice and the time progression helps clear up what's going on a lot.  

I notice that the legend colours dance around a bit, so that one frame's precipitation legend value is not necessarily the same as the next (i.e. 64-100 mm/h is violet, then burgundy, 16-24  mm/h is yellow, then orange)...   Any way the graphic could use fixed colours for consistency?

![DancingScaleValues](https://user-images.githubusercontent.com/4991612/89328074-d3fa0500-d65a-11ea-84e2-65d8ab7ddfb3.gif)

**Comment by michaeldavie** [comment]
Thanks, I've noticed that but I'm not sure how to resolve it yet.

**Comment by stevendinardo** [comment]
It looks like each individual frame does have the correct colours but the GIF format is limited to only 256 colours.

This could be fixed by changing format to MP4 instead of GIF. It would also have the benefit of not creating a 10MB gif but I'm not sure how it would affect things like looping in Home Assistant or if HA could even play a video like that. The image dimensions would need to be divisible by 16 for mp4 compatibility and adds imageio-ffmpeg as a dependency.

https://github.com/michaeldavie/env_canada/blob/6b3a2ce0ad6e5ddf9d18f46a66afcd658c01386c/env_canada/ec_radar.py#L262

**Comment by michaeldavie** [comment]
Thanks for looking into this! I tried using the `subrectangles()` method, but while this did make the GIF file smaller the colour shifting is still there. I'm going to take a look at using `quantize()` on the individual PNG frames before they get assembled into the GIF.

**Comment by michaeldavie** [comment]
Success!

![fixed_loop](https://user-images.githubusercontent.com/16008714/113033383-f4814d00-915e-11eb-96ef-92b31d80e66a.gif)

**Comment by michaeldavie** [comment]
Fixed by bfe7c83e19444090c3e7d52cb14e1d71d6e13142

**Comment by stevendinardo** [comment]
Awesome. This works well with the transparency too. Maybe we could set the default opacity to something other than 100. I could make the PR if you would like.

**Comment by michaeldavie** [comment]
That's a good point...I think 65% looks good so I'll set that as the default.
